[styles]
prefix = "qas-"
page_gutter_x = "page-gutter-x"
branding = "brand" 
# header/navigation
site_header = "site-header"
site_header_main = "site-header-main"
site_navigation = "site-navigation"
sticky_header = "sticky-header"
primary_menu = "primary-menu"
menu_container = "menu-container"
menu_item = "menu-item"
menu_toggle = "menu-toggle"
menu_toggles = "menu-toggles"
menu_open = "menu-open"
menu_fade = "menu-fade"
mobile_primary = "mobile-primary"
mobile_secondary = "mobile-secondary"
# animation
is_animated = "is-animated"
ani = "ani"
has_motion = "has-motion"
# main
main_id = "main"
# body
page_head = "page-head"
hero = "hero"
container = "container"
section = "section"
prev_next = "prev-next"
site_footer = "site-footer"
card = "card"
# breakpoints
breakpoint_sm = "576px"
breakpoint_md = "768px"
breakpoint_lg = "992px"
breakpoint_xl = "1200px"
breakpoint_xxl = "1400px"
breakpoint_xxxl = "2300px"
breakpoint_mobile = "992px"